---

- name: add ppa repository
  apt_repository:
    repo: 'ppa:bit-team/stable'
    state: present
    update_cache: yes
  become: yes
  become_user: root

- name: install backintime-kde
  apt:
    name: backintime-kde
    state: present
  become: yes
  become_user: root
